### PR TITLE
Add support for custom headers

### PR DESCRIPTION
**Pull request by gabifoot**
This pull reequest aims to add support for uploading objects to a container with custom headers.

### CODE REVIEW

**Comment by tulios** [comment]
Hi @gabifoot, thanks for the PR. I'll approve it here, can you update the readme as well?

**Comment by gabifoot** [comment]
Hi. Sure, I'll update and commit it.

**Comment by tulios** [comment]
:+1:

**Comment by gabifoot** [comment]
@tulios Done! Thank you, man. :)

**Pull request merged**
