### PR TITLE
Add support to Keystone v3

### LINKED ISSUE #34: Support Identity v3
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Currently the Nightcrawler Swift does not work with providers that require support for Identity v3.

Would it be possible to add support for Identity v3 in this project as well?

### PR DESCRIPTION
**Pull request by ggarnier**
This PR adds support to Keystone API v3, and also breaks compatibility with v2. That means you should upgrade the gem major version to reflect the API breaking changes.

Fixes #34

### CODE REVIEW

**Comment by tulios** [comment]
Nice stuff, can you just update the readme with a section like:

for swift version X use nightcrawler_swift vX (url)
for version Y use vY (url)

**Comment by tulios** [comment]
We also have to bump the version (version 2?)

**Comment by ggarnier** [comment]
Current version is `0.11.1`. I was thinking about bumping to `1.0.0`

**Review by tulios — APPROVED** [review]

**Comment by tulios** [comment]
Merge at will! 🎉

**Pull request merged**
